exclude: |
    (?x)(
        tests/|
        docs/|
        core/migrations/|
        venv/|
        migrations/|
        manage.py|
        __about__.py
    )
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.1
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: mypy
        name: MyPy
        entry: |
          mypy
          --ignore-missing-imports
          --install-types
          --non-interactive
          --strict
          --implicit-reexport
          --warn-unused-ignores
          --cache-fine-grained
          --no-namespace-packages
        files: \.py$
        language: python

      - id: pylint
        name: Pylint
        entry: |
          bash -c 'PYTHONPATH=. pylint \
          --max-line-length=99 \
          --ignore-imports=yes \
          --load-plugins=pylint_django \
          --django-settings-module=core.settings \
          "$@"' --
        files: \.py$
        language: python
