version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lexiflux-postgres-koyeb
    environment:
      POSTGRES_DB: lexiflux
      POSTGRES_USER: lexiflux
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lexiflux"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
