services:
  allure:
    image: andgineer/allure
    command: /bin/sh -c "allure serve -p 80 /allure-results"
    ports:
      - "8800:80"
    volumes:
      - ${PWD}/allure-results:/allure-results

  chrome:
    image: seleniarm/node-chromium
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - HUB_HOST=hub
      - HUB_PORT=4444

  edge:
    image: selenium/node-edge:4.9.1-20230508
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - HUB_HOST=hub
      - HUB_PORT=4444

  firefox:
    image: seleniarm/node-firefox
    shm_size: 2gb
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - HUB_HOST=hub
      - HUB_PORT=4444

  hub:
    image: seleniarm/hub
    ports:
      - "4444:4444"
