FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y build-essential

WORKDIR /app

COPY core /core
COPY lexiflux /lexiflux
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

