# Generated by Django 5.0 on 2024-07-05 06:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "google_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("epub_code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=100, unique=True)),
                ("public", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=200)),
                ("toc_json", models.TextField(blank=True, default="{}", null=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lexiflux.author",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_with",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_books",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="lexiflux.language",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_blob", models.BinaryField()),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_file",
                        to="lexiflux.book",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReaderProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inline_translation_type",
                    models.CharField(
                        choices=[
                            ("Translate", "Translate"),
                            ("Sentence", "Sentence"),
                            ("Explain", "Explain"),
                            ("Examples", "Examples"),
                            ("Lexical", "Lexical"),
                            ("Dictionary", "Dictionary"),
                            ("Site", "Site"),
                        ],
                        max_length=20,
                    ),
                ),
                ("inline_translation_parameters", models.JSONField(default=dict)),
                (
                    "current_book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="current_readers",
                        to="lexiflux.book",
                    ),
                ),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile_language",
                        to="lexiflux.language",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reader_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_language",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="profile_user_language",
                        to="lexiflux.language",
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "language")},
            },
        ),
        migrations.CreateModel(
            name="ReadingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_number", models.PositiveIntegerField()),
                ("top_word_id", models.PositiveIntegerField()),
                ("read_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lexiflux.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-read_time"],
            },
        ),
        migrations.CreateModel(
            name="BookPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                ("content", models.TextField()),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pages",
                        to="lexiflux.book",
                    ),
                ),
            ],
            options={
                "ordering": ["number"],
                "unique_together": {("book", "number")},
            },
        ),
        migrations.CreateModel(
            name="LexicalArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Translate", "Translate"),
                            ("Sentence", "Sentence"),
                            ("Explain", "Explain"),
                            ("Examples", "Examples"),
                            ("Lexical", "Lexical"),
                            ("Dictionary", "Dictionary"),
                            ("Site", "Site"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("parameters", models.JSONField(default=dict)),
                (
                    "reader_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lexical_articles",
                        to="lexiflux.readerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("reader_profile", "title")},
            },
        ),
        migrations.CreateModel(
            name="ReadingLoc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page_number",
                    models.PositiveIntegerField(
                        help_text="Page number currently being read"
                    ),
                ),
                (
                    "word",
                    models.PositiveIntegerField(
                        help_text="Last word read on the current reading page"
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "furthest_reading_page",
                    models.PositiveIntegerField(
                        default=0, help_text="Stores the furthest reading page number"
                    ),
                ),
                (
                    "furthest_reading_word",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Stores the furthest reading top word on the furthest page",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lexiflux.book"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_pos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "book")},
            },
        ),
    ]
