# Generated by Django 5.0 on 2024-07-02 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexiflux", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LexicalArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Translate", "Translate"),
                            ("Sentence", "Sentence"),
                            ("Explain", "Explain"),
                            ("Examples", "Examples"),
                            ("Lexical", "Lexical"),
                            ("Dictionary", "Dictionary"),
                            ("Site", "Site"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("parameters", models.JSONField(default=dict)),
                (
                    "reader_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lexical_articles",
                        to="lexiflux.readerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("reader_profile", "title")},
            },
        ),
    ]
