# Generated by Django 5.0 on 2024-06-30 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexiflux", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookpage",
            name="_words",
            field=models.JSONField(blank=True, db_column="words", default=list),
        ),
    ]
