# Generated by Django 5.0 on 2024-08-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0002_bookimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lexicalarticle',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='lexicalarticle',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
