# Generated by Django 5.1 on 2024-08-16 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0003_alter_lexicalarticle_options_lexicalarticle_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readinghistory',
            options={},
        ),
        migrations.RenameField(
            model_name='readinghistory',
            old_name='read_time',
            new_name='last_opened',
        ),
        migrations.RenameField(
            model_name='readingloc',
            old_name='updated',
            new_name='last_access',
        ),
        migrations.AlterUniqueTogether(
            name='readinghistory',
            unique_together={('user', 'book')},
        ),
        migrations.AddField(
            model_name='readinghistory',
            name='last_position_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='readingloc',
            name='current_jump',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='readingloc',
            name='jump_history',
            field=models.JSONField(default=list),
        ),
        migrations.RemoveField(
            model_name='readinghistory',
            name='page_number',
        ),
        migrations.RemoveField(
            model_name='readinghistory',
            name='top_word_id',
        ),
    ]
