# Generated by Django 5.0 on 2024-07-03 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexiflux", "0003_readerprofile_inline_translation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="readerprofile",
            name="inline_translation",
        ),
        migrations.AddField(
            model_name="readerprofile",
            name="inline_translation_parameters",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="readerprofile",
            name="inline_translation_type",
            field=models.CharField(
                choices=[
                    ("Translate", "Translate"),
                    ("Sentence", "Sentence"),
                    ("Explain", "Explain"),
                    ("Examples", "Examples"),
                    ("Lexical", "Lexical"),
                    ("Dictionary", "Dictionary"),
                    ("Site", "Site"),
                ],
                default="Dictionary",
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
