# Generated by Django 5.1 on 2024-08-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0004_alter_readinghistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingloc',
            name='last_position_percent',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='ReadingHistory',
        ),
    ]
