# Generated by Django 5.1 on 2024-08-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0007_alter_readingloc_furthest_reading_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingloc',
            name='last_access',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
