# Generated by Django 5.1 on 2024-09-22 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0008_alter_readingloc_last_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(help_text='Term looked up for translation', max_length=255)),
                ('context', models.TextField(help_text='Context of the term')),
                ('lookup_count', models.PositiveIntegerField(default=1, help_text='Number of lookups')),
                ('first_lookup', models.DateTimeField(auto_now_add=True, help_text='First lookup timestamp')),
                ('last_lookup', models.DateTimeField(auto_now=True, help_text='Most recent lookup timestamp')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to='lexiflux.book')),
                ('source_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to='lexiflux.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_translation_history', to='lexiflux.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['term', 'source_language', 'user'], name='lexiflux_tr_term_56fbc5_idx'), models.Index(fields=['last_lookup'], name='lexiflux_tr_last_lo_8319cb_idx'), models.Index(fields=['lookup_count'], name='lexiflux_tr_lookup__49f6b1_idx')],
                'unique_together': {('term', 'source_language', 'user')},
            },
        ),
    ]
