# Generated by Django 5.1.1 on 2024-10-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0011_translationhistory_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsexport',
            name='deck_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
