# Generated by Django 5.1.1 on 2024-10-05 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0012_wordsexport_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsexport',
            name='export_format',
            field=models.CharField(default='ankiConnect', max_length=20),
        ),
        migrations.AlterField(
            model_name='wordsexport',
            name='details',
            field=models.JSONField(default=dict, help_text='Details of the export'),
        ),
    ]
