# Generated by Django 5.1.1 on 2024-10-10 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0013_wordsexport_export_format_alter_wordsexport_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordsexport',
            name='export_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
