# Generated by Django 5.1.1 on 2024-10-10 15:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0014_alter_wordsexport_export_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationhistory',
            name='first_lookup',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='First lookup timestamp'),
        ),
        migrations.AlterField(
            model_name='translationhistory',
            name='last_lookup',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Most recent lookup timestamp'),
        ),
    ]
