# Generated by Django 5.1.4 on 2025-01-03 08:43

from django.db import migrations, models
from lexiflux.lexiflux_settings import settings


def update_default_user(apps, schema_editor):
    """Update the default user with approved and premium status."""
    User = apps.get_model('lexiflux', 'CustomUser')
    default_username = settings.lexiflux.default_user_name

    User.objects.filter(username=default_username).update(
        is_approved=True,
        premium=True,
        email=settings.lexiflux.default_user_email
    )


class Migration(migrations.Migration):
    dependencies = [
        ('lexiflux', '0017_bookpage_normalized_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            update_default_user,
            reverse_code=migrations.RunPython.noop
        ),
    ]