# Generated by Django 5.1.5 on 2025-01-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0018_auto_20250103_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagepreferences',
            name='inline_translation_type',
            field=models.CharField(choices=[('Translate', 'Translate'), ('Sentence', 'Sentence'), ('Explain', 'Explain'), ('Origin', 'Origin'), ('Lexical', 'Lexical'), ('AI', 'AI'), ('Dictionary', 'Dictionary'), ('Site', 'Site')], default='Translate', max_length=20),
        ),
        migrations.AlterField(
            model_name='lexicalarticle',
            name='type',
            field=models.CharField(choices=[('Translate', 'Translate'), ('Sentence', 'Sentence'), ('Explain', 'Explain'), ('Origin', 'Origin'), ('Lexical', 'Lexical'), ('AI', 'AI'), ('Dictionary', 'Dictionary'), ('Site', 'Site')], max_length=20),
        ),
    ]
