# Generated by Django 5.1.5 on 2025-01-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0019_alter_languagepreferences_inline_translation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_with_language', to='lexiflux.language'),
        ),
    ]
