# Generated by Django 5.2.1 on 2025-07-27 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexiflux", "0020_customuser_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="anchor_map",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Maps anchors to page numbers and EPUB items. anchor -> {`page`: .., `item_id``: .., item_name``: ..}",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="toc",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Table of contents: (title, page, word)",
            ),
        ),
        migrations.CreateModel(
            name="APIToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(db_index=True, max_length=64, unique=True)),
                ("name", models.CharField(default="Calibre Plugin", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "lexiflux_api_token",
            },
        ),
    ]
