# Generated by Django 5.2.8 on 2025-11-22 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lexiflux", "0021_alter_book_anchor_map_alter_book_toc_apitoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="languagepreferences",
            name="inline_translation_type",
            field=models.CharField(
                choices=[
                    ("Dictionary", "Dictionary"),
                    ("Site", "Site"),
                    ("AI dictionary", "AI dictionary"),
                    ("Translate", "Translate"),
                    ("Sentence", "Sentence"),
                    ("Explain", "Explain"),
                    ("Lexical", "Lexical"),
                    ("Origin", "Origin"),
                    ("AI", "AI"),
                ],
                default="Translate",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lexicalarticle",
            name="type",
            field=models.CharField(
                choices=[
                    ("Dictionary", "Dictionary"),
                    ("Site", "Site"),
                    ("AI dictionary", "AI dictionary"),
                    ("Translate", "Translate"),
                    ("Sentence", "Sentence"),
                    ("Explain", "Explain"),
                    ("Lexical", "Lexical"),
                    ("Origin", "Origin"),
                    ("AI", "AI"),
                ],
                max_length=20,
            ),
        ),
    ]
