# Generated by Django 6.0.5 on 2026-09-24 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0022_alter_languagepreferences_inline_translation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagepreferences',
            name='inline_translation_type',
            field=models.CharField(choices=[('Dictionary', 'Dictionary'), ('Site', 'Site'), ('AI dictionary', 'AI dictionary'), ('In depth', 'In depth'), ('Translate', 'Translate'), ('Sentence', 'Sentence'), ('Explain', 'Explain'), ('Lexical', 'Lexical'), ('Origin', 'Origin'), ('AI', 'AI')], default='Translate', max_length=20),
        ),
        migrations.AlterField(
            model_name='lexicalarticle',
            name='type',
            field=models.CharField(choices=[('Dictionary', 'Dictionary'), ('Site', 'Site'), ('AI dictionary', 'AI dictionary'), ('In depth', 'In depth'), ('Translate', 'Translate'), ('Sentence', 'Sentence'), ('Explain', 'Explain'), ('Lexical', 'Lexical'), ('Origin', 'Origin'), ('AI', 'AI')], max_length=20),
        ),
        migrations.DeleteModel(
            name='AIModelConfig',
        ),
    ]
