# Generated by Django 6.0.5 on 2026-09-25 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0023_llmbroker'),
    ]

    operations = [
        migrations.CreateModel(
            name='WiktionaryPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('user_language', models.CharField(max_length=16)),
                ('content', models.JSONField(blank=True, null=True)),
                ('fetched', models.DateTimeField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('url', 'user_language'), name='wiktionary_page_url_user_language')],
            },
        ),
    ]
