# Generated by Django 6.0.5 on 2026-09-26 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lexiflux', '0024_wiktionarypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationhistory',
            name='translation_from_llm',
            field=models.BooleanField(default=False, help_text='The translation is the LLM translation of the term in its passage'),
        ),
    ]
