# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: lexiflux
site_url: https://lexiflux.sorokin.engineer/
site_author: Andrey Sorokin

# Repository
repo_name: lexiflux
repo_url: https://github.com/andgineer/lexiflux
edit_uri: edit/master/docs
docs_dir: 'src/LANGUAGE'
site_dir: 'SITE_DIR'

plugins:
  - awesome-pages
  - search:
      lang: LANGUAGE
  - mkdocstrings:
        handlers:
          python:
            options:
              show_root_heading: true

markdown_extensions:
  - abbr
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: 'docs/includes'
  - admonition

theme:
  name: material
  features:
    - toc.integrate
    - navigation.tracking
    - content.code.copy

extra:
  alternate:
    - name: English
      link: /lexiflux/
      lang: en
    - name: Русский
      link: /lexiflux/ru/
      lang: ru

nav:
  - index.md
  - quickstart.md
  - docker.md
  - aimodels.md
