# This workflow build and push Docker image to docker hub.
# And create a release on GitHub.
# https://docs.docker.com/build/ci/github-actions/cache/
name: dockerhub

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write
  actions: read
  issues: write
  pull-requests: write

jobs:
  check_release:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    outputs:
      release_version: ${{ steps.check_tag.outputs.release_version }}
      release_tag: ${{ steps.check_tag.outputs.release_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags -f

      - name: Check for tag and extract version
        id: check_tag
        run: |
          COMMIT_SHA="${{ github.event.workflow_run.head_sha }}"
          TAG=$(git tag --points-at $COMMIT_SHA | grep '^v' | sort -V | tail -n 1)
          if [ -n "$TAG" ]; then
            VERSION=$(echo $TAG | cut -c 2-)
            echo "release_version=$VERSION" >> $GITHUB_OUTPUT
            echo "release_tag=$TAG" >> $GITHUB_OUTPUT
            echo "Tag found: $TAG, Version: $VERSION"
          else
            echo "No tag found for commit $COMMIT_SHA"
          fi

  build:
    needs: check_release
    if: needs.check_release.outputs.release_version != ''
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lexiflux:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/lexiflux:${{ needs.check_release.outputs.release_version }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
          platforms: |-
            linux/amd64
            linux/arm64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.check_release.outputs.release_tag }}
          release_name: Release ${{ needs.check_release.outputs.release_version }}
          body:  |
            Release for version v${{ needs.check_release.outputs.release_version }}
            Docker image: https://hub.docker.com/r/andgineer/lexiflux/tags?page=&page_size=&ordering=&name=${{ needs.check_release.outputs.release_version }}
          draft: false
          prerelease: false

  no_release:
    needs: check_release
    if: needs.check_release.outputs.release_version == ''
    runs-on: ubuntu-latest
    steps:
      - name: No release version found
        run: |
          echo "No release tag found. Skipping publication to Docker Hub."

