# This workflow build and push Docker image to docker hub
# https://docs.docker.com/build/ci/github-actions/cache/
name: dockerhub

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version var
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/} | cut -c 2-)" >> $GITHUB_ENV
          echo $RELEASE_VERSION

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to docker hub
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lexiflux:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/lexiflux:${{ env.RELEASE_VERSION }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
          platforms: |-
            linux/amd64
            linux/arm64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
