# This workflow build and push Docker image to docker hub
# https://docs.docker.com/build/ci/github-actions/cache/
name: dockerhub

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract version from tag
        run: |
          echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/*/} | cut -c 2-)" >> $GITHUB_ENV
        env:
          GITHUB_REF: ${{ github.event.workflow_run.head_branch }}

      - name: Set up QEMU
        if: env.RELEASE_VERSION != ''
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.RELEASE_VERSION != ''
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: env.RELEASE_VERSION != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to docker hub
        if: env.RELEASE_VERSION != ''
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lexiflux:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/lexiflux:${{ env.RELEASE_VERSION }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
          platforms: |-
            linux/amd64
            linux/arm64

      - name: Image digest
        if: env.RELEASE_VERSION != ''
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Create Release
        if: env.RELEASE_VERSION != ''
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body: https://hub.docker.com/r/andgineer/lexiflux
          draft: false
          prerelease: false
