# This workflow build and push Docker image to docker hub.
# And create a release on GitHub.
# https://docs.docker.com/build/ci/github-actions/cache/
name: dockerhub

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: write
  actions: read
  issues: write
  pull-requests: write

jobs:
  build:
    if: github.event.workflow_run.conclusion == 'success'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch tags
        run: git fetch --tags -f

      - name: Check for tag and extract version
        id: check_tag
        run: |
          COMMIT_SHA="${{ github.event.workflow_run.head_sha }}"
          TAG=$(git tag --points-at $COMMIT_SHA | grep '^v' | sort -V | tail -n 1)
          if [ -n "$TAG" ]; then
            VERSION=$(echo $TAG | cut -c 2-)
            echo "RELEASE_VERSION=$VERSION" >> $GITHUB_ENV
            echo "RELEASE_TAG=$TAG" >> $GITHUB_ENV
            echo "Tag found: $TAG, Version: $VERSION"
          else
            echo "No tag found for commit $COMMIT_SHA"
          fi

      - name: Set up QEMU
        if: env.RELEASE_VERSION != ''
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: env.RELEASE_VERSION != ''
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: env.RELEASE_VERSION != ''
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push to docker hub
        if: env.RELEASE_VERSION != ''
        uses: docker/build-push-action@v5
        with:
          context: ./
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/lexiflux:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/lexiflux:${{ env.RELEASE_VERSION }}
          cache-from: type=registry,ref=user/app:latest
          cache-to: type=inline
          platforms: |-
            linux/amd64
            linux/arm64

      - name: Image digest
        if: env.RELEASE_VERSION != ''
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Create Release
        if: env.RELEASE_VERSION != ''
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          release_name: Release ${{ env.RELEASE_VERSION }}
          body:  |
            Release for version v${{ env.RELEASE_VERSION }}
            Docker image: https://hub.docker.com/r/andgineer/lexiflux/tags?page=&page_size=&ordering=&name=${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false
