# build docs from docstrings and markdown-file in folder docs
# publish them as github pages
#
#note for myself
#
# Do not forget to set git branch `gh-pages` as source for github pages.
# This branch auto-updated by `mkdocs gh-deploy`
#
name: static source code checks
on:
  push:
    branches:
      - main
      - master
jobs:
  static:
    runs-on: ubuntu-latest
    env:
      PRIMARY_PYTHON_VERSION: '3.12'
      DJANGO_SETTINGS_MODULE: 'lexiflux.settings'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ env.PRIMARY_PYTHON_VERSION  }}
      - uses: andgineer/uv-venv@v1
      - run: |
          uv pip install pip -r requirements.dev.txt
          pre-commit run --verbose --all-files
